version: 0.2

phases:
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm run build
      - ls -al
      - ls -al dist
  post_build:
    commands:
      - aws cloudfront create-invalidation \
        --distribution-id $CLOUDFRONT_DISTRIBUTION_ID \
        --paths "/*"

artifacts:
  files:
    - "**/*"
  base-directory: dist
