version: 0.2

phases:
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm run build
      - ls -al
      - ls -al dist

artifacts:
  files:
    - '**/*'
  base-directory: dist
